// this file is generated by build.rs
// do not modify it directly

use crate::gameobjtype::GameObjectTypeBuilder;

pub mod test;
pub mod test_tile;
pub mod player;
pub mod tree;

pub const TYPES: [GameObjectTypeBuilder; 4] = [
    test::TYPE,
    test_tile::TYPE,
    player::TYPE,
    tree::TYPE,
];
