[package]
name = "minefred"
version = "0.1.0"
edition = "2024"

[dependencies]
hecs = "0.10.5"
rand = "0.9.2"
serde = "1.0.219"
serde_json = "1.0.141"
eyre = "0.6.12"
unicode-segmentation = "1.12.0"

[dependencies.sdl2]
version = "0.38.0"
features = ["ttf"]
