// this file is generated by build.rs
// do not modify it directly

use crate::gameobjtype::GameObjectType;

mod test;
mod test_tile;
mod player;
mod tree;

pub const TYPES: [GameObjectType; 4] = [
    test::TYPE,
    test_tile::TYPE,
    player::TYPE,
    tree::TYPE,
];
